(function ( Guia ) {
    'use strict';

    /*
     * O caminho que uma ação percorre pelas classes do projeto, do clique ao banco e de volta.
     * Os nomes de classe e de método são os mesmos em todas as linguagens; só o caminho do
     * arquivo muda, por isso cada ator guarda um caminho por linguagem.
     */

    /* Atalhos para não repetir a mesma lista de caminhos em cada ator. */
    const arquivoBackend = ( php, hifen, java ) => ( {
        camada: 'backend',
        php: 'backend/src/' + php,
        typescript: 'backend/src/' + hifen + '.ts',
        javascript: 'backend/src/' + hifen + '.js',
        java: 'backend/src/main/java/biblioteca/' + java,
    } );

    const arquivoFrontend = caminho => ( {
        camada: 'frontend',
        typescript: 'frontend/src/' + caminho + '.ts',
        javascript: 'frontend/src/' + caminho + '.js',
    } );

    const ARQUIVOS = {
        visao: arquivoFrontend( 'emprestimo/visao-emprestimos-em-html' ),
        controladora: arquivoFrontend( 'emprestimo/controladora-emprestimos' ),
        servico: arquivoFrontend( 'emprestimo/servico-emprestimos' ),
        rotas: arquivoBackend( 'emprestimo/rotas.php', 'emprestimo/rotas', 'emprestimo/RotasEmprestimos.java' ),
        gestor: arquivoBackend( 'emprestimo/GestorEmprestimos.php', 'emprestimo/gestor-emprestimos', 'emprestimo/GestorEmprestimos.java' ),
        emprestimo: arquivoBackend( 'emprestimo/Emprestimo.php', 'emprestimo/emprestimo', 'emprestimo/Emprestimo.java' ),
        leitor: arquivoBackend( 'leitor/Leitor.php', 'leitor/leitor', 'leitor/Leitor.java' ),
        repositorio: arquivoBackend( 'emprestimo/RepositorioEmprestimosEmBDR.php', 'emprestimo/repositorio-emprestimos-em-bdr', 'emprestimo/RepositorioEmprestimosEmBDR.java' ),
        repositorioLivros: arquivoBackend( 'livro/RepositorioLivrosEmBDR.php', 'livro/repositorio-livros-em-bdr', 'livro/RepositorioLivrosEmBDR.java' ),
        repositorioLeitores: arquivoBackend( 'leitor/RepositorioLeitoresEmBDR.php', 'leitor/repositorio-leitores-em-bdr', 'leitor/RepositorioLeitoresEmBDR.java' ),
    };

    /* As colunas do diagrama, na ordem em que aparecem. */
    const atores = [
        { id: 'usuario', papel: 'Você', classe: 'no navegador', camada: 'ator' },
        { id: 'visao', papel: 'Visão', classe: 'VisaoEmprestimosEmHtml', camada: 'frontend', arquivo: ARQUIVOS.visao },
        { id: 'controladora', papel: 'Controladora', classe: 'ControladoraEmprestimos', camada: 'frontend', arquivo: ARQUIVOS.controladora },
        { id: 'servico', papel: 'Serviço', classe: 'ServicoEmprestimos', camada: 'frontend', arquivo: ARQUIVOS.servico },
        { id: 'rotas', papel: 'Rotas', classe: 'rotas de /emprestimos', camada: 'backend', arquivo: ARQUIVOS.rotas },
        { id: 'gestor', papel: 'Gestor', classe: 'GestorEmprestimos', camada: 'backend', arquivo: ARQUIVOS.gestor },
        { id: 'entidade', papel: 'Entidades', classe: 'Emprestimo · Leitor', camada: 'backend', arquivo: ARQUIVOS.emprestimo },
        { id: 'repositorio', papel: 'Repositório', classe: 'Repositórios em BDR', camada: 'backend', arquivo: ARQUIVOS.repositorio },
        { id: 'banco', papel: 'Banco', classe: 'MariaDB', camada: 'banco' },
    ];

    const cenarios = [
        {
            id: 'registrar',
            titulo: 'Emprestar um livro',
            resumo: 'Você escolhe o livro e o leitor e clica em Emprestar. É o caminho completo: passa pelas três classes do front-end, atravessa a rede, percorre as quatro camadas do back-end, grava no banco e volta até a tela.',
            passos: [
                {
                    de: 'usuario', para: 'visao', tipo: 'chamada',
                    rotulo: 'escolhe o livro e o leitor, clica em Emprestar',
                    titulo: 'O navegador avisa a visão',
                    texto: 'Os dois <code>&lt;select&gt;</code> e o botão estão no HTML da página. Ao enviar o formulário, o navegador dispara o evento <code>submit</code>, e quem está ouvindo esse evento é a visão.',
                },
                {
                    de: 'visao', para: 'controladora', tipo: 'chamada',
                    rotulo: 'registrar( livroId, leitorId )',
                    titulo: 'A visão avisa a controladora, e só',
                    texto: 'A visão lê o valor dos campos, converte para número e chama a função que a controladora registrou em <code>aoRegistrar</code>. Ela não decide nada: não valida, não chama a API. É a única classe que conhece os ids do HTML.',
                    arquivo: ARQUIVOS.visao,
                },
                {
                    de: 'controladora', para: 'servico', tipo: 'chamada',
                    rotulo: 'registrar( livroId, leitorId )',
                    titulo: 'A controladora coordena',
                    texto: 'A controladora é o meio de campo do MVP: recebe a ação da visão e pede o trabalho ao serviço. Ela não usa <code>document</code> nem <code>fetch</code> — por isso os testes de unidade dela rodam sem navegador e sem servidor.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'servico', para: 'rotas', tipo: 'rede',
                    rotulo: 'POST /emprestimos  { livroId, leitorId }',
                    titulo: 'Aqui a chamada vira rede',
                    texto: 'O serviço é a única classe do front-end que conhece a API. Ele monta a requisição com <code>fetch</code> e envia o corpo em JSON. Deste ponto em diante o código roda em outro processo, no servidor — e pode estar em outra linguagem.',
                    arquivo: ARQUIVOS.servico,
                },
                {
                    de: 'rotas', para: 'gestor', tipo: 'chamada',
                    rotulo: 'registrar( dados, hoje )',
                    titulo: 'A rota só traduz HTTP',
                    texto: 'A rota lê o corpo da requisição e chama o gestor. Ela não tem regra de negócio nenhuma: existe para transformar HTTP em chamada de método e, na volta, o resultado em JSON.',
                    arquivo: ARQUIVOS.rotas,
                },
                {
                    de: 'gestor', para: 'repositorio', tipo: 'chamada',
                    rotulo: 'livros.obterPorId( livroId )',
                    titulo: 'O gestor busca o livro',
                    texto: 'O gestor conhece os repositórios pela <strong>interface</strong>, não pela classe concreta. Quem entregou o <code>RepositorioLivrosEmBDR</code> foi a rota, no momento de montar o gestor. Nos testes, entra um dublê no lugar.',
                    arquivo: ARQUIVOS.repositorioLivros,
                },
                {
                    de: 'repositorio', para: 'banco', tipo: 'sql',
                    rotulo: 'SELECT id, titulo, autor, ano FROM livro WHERE id = ?',
                    titulo: 'O repositório fala SQL',
                    texto: 'Esta é a única camada que escreve SQL. O <code>?</code> não é enfeite: o valor viaja separado do comando, o que impede SQL Injection.',
                    arquivo: ARQUIVOS.repositorioLivros,
                },
                {
                    de: 'banco', para: 'repositorio', tipo: 'retorno',
                    rotulo: 'uma linha da tabela',
                    titulo: 'O banco devolve linhas, não objetos',
                    texto: 'O que volta do banco é um array de colunas. Converter isso em um objeto <code>Livro</code> é trabalho do repositório — é o que separa o resto do sistema do formato das tabelas.',
                    arquivo: ARQUIVOS.repositorioLivros,
                },
                {
                    de: 'repositorio', para: 'gestor', tipo: 'retorno',
                    rotulo: 'Livro',
                    titulo: 'Daqui para cima, só objetos',
                    texto: 'O gestor recebe um <code>Livro</code>. Se não existisse livro com aquele id, o repositório devolveria <code>null</code> e o gestor lançaria <code>DominioException</code> com "Livro não encontrado."',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'gestor', para: 'repositorio', tipo: 'chamada',
                    rotulo: 'leitores.obterPorId( leitorId )',
                    titulo: 'E agora o leitor',
                    texto: 'Mesmo caminho do livro, por outro repositório: <code>SELECT ... FROM leitor WHERE id = ?</code>, e a linha vira um objeto <code>Leitor</code>.',
                    arquivo: ARQUIVOS.repositorioLeitores,
                },
                {
                    de: 'repositorio', para: 'gestor', tipo: 'retorno',
                    rotulo: 'Leitor',
                    titulo: 'O gestor tem os dois objetos',
                    texto: 'Com o livro e o leitor em mãos, começam as verificações das regras de negócio.',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'gestor', para: 'repositorio', tipo: 'chamada',
                    rotulo: 'emprestimos.livroEstaEmprestado( livro.id )',
                    titulo: 'Regra R4 — um livro por vez',
                    texto: 'Um livro emprestado não pode sair de novo. O repositório conta os empréstimos daquele livro com <code>data_devolucao IS NULL</code>. Se já houvesse um, o gestor lançaria "O livro já está emprestado."',
                    destaque: 'regra',
                    arquivo: ARQUIVOS.repositorio,
                },
                {
                    de: 'repositorio', para: 'gestor', tipo: 'retorno',
                    rotulo: 'false — o livro está livre',
                    titulo: 'Livro liberado',
                    texto: 'A contagem voltou zero: ninguém está com este livro. O gestor segue para a próxima regra.',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'gestor', para: 'repositorio', tipo: 'chamada',
                    rotulo: 'emprestimos.contarEmAbertoDoLeitor( leitor.id )',
                    titulo: 'Quantos o leitor já tem?',
                    texto: 'O gestor não decide o limite aqui — ele só levanta o número. A decisão é de quem conhece a regra: a entidade <code>Leitor</code>.',
                    arquivo: ARQUIVOS.repositorio,
                },
                {
                    de: 'repositorio', para: 'gestor', tipo: 'retorno',
                    rotulo: '1',
                    titulo: 'Um empréstimo em aberto',
                    texto: 'Esse número sozinho não significa nada. Falta perguntar à entidade se, com um empréstimo em aberto, este leitor pode pegar outro.',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'gestor', para: 'entidade', tipo: 'chamada',
                    rotulo: 'leitor.podePegarEmprestado( 1 )',
                    titulo: 'Regra R3 — quem decide é a entidade',
                    texto: 'Este é o coração da modelagem orientada a objetos: a regra do limite de empréstimos mora dentro de <code>Leitor</code>, junto do dado que ela usa. O gestor apenas pergunta. Se a regra mudar, muda em um lugar só.',
                    destaque: 'regra',
                    arquivo: ARQUIVOS.leitor,
                },
                {
                    de: 'entidade', para: 'gestor', tipo: 'retorno',
                    rotulo: 'true',
                    titulo: 'Pode emprestar',
                    texto: 'Todas as regras passaram. Só agora o gestor vai gravar. Repare que nada foi escrito no banco até aqui: primeiro valida, depois grava.',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'gestor', para: 'repositorio', tipo: 'chamada',
                    rotulo: 'emprestimos.adicionar( new Emprestimo( 0, livro, leitor, hoje ) )',
                    titulo: 'O gestor monta a entidade e manda gravar',
                    texto: 'O <code>0</code> no lugar do id significa "ainda não tem id" — quem dá o id é o banco. O gestor entrega um objeto pronto; como ele vira linha de tabela não é problema dele.',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'repositorio', para: 'banco', tipo: 'sql',
                    rotulo: 'INSERT INTO emprestimo ( livro_id, leitor_id, data_emprestimo ) VALUES ( ?, ?, ? )',
                    titulo: 'Aqui o empréstimo é salvo',
                    texto: 'Este é o único ponto de toda a rota em que algo é gravado. O repositório desmonta o objeto <code>Emprestimo</code> em colunas e executa o INSERT.',
                    destaque: 'grava',
                    arquivo: ARQUIVOS.repositorio,
                },
                {
                    de: 'banco', para: 'repositorio', tipo: 'retorno',
                    rotulo: 'id = 7  (AUTO_INCREMENT)',
                    titulo: 'O banco devolve o id criado',
                    texto: 'A coluna <code>id</code> é <code>AUTO_INCREMENT</code>: o banco gera o número. O repositório lê esse valor com <code>lastInsertId()</code> e o devolve.',
                    arquivo: ARQUIVOS.repositorio,
                },
                {
                    de: 'repositorio', para: 'gestor', tipo: 'retorno',
                    rotulo: '7',
                    titulo: 'De volta ao gestor',
                    texto: 'Com o id em mãos, o gestor monta a resposta: os dados do empréstimo mais o que as entidades calculam na hora — a data limite, os dias de atraso e a multa.',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'gestor', para: 'rotas', tipo: 'retorno',
                    rotulo: 'dados do empréstimo',
                    titulo: 'Objetos viram dados simples',
                    texto: 'O gestor devolve uma estrutura simples, sem objetos de domínio. Assim a rota não precisa saber nada sobre as entidades para produzir o JSON.',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'rotas', para: 'servico', tipo: 'rede',
                    rotulo: '201 Created  +  JSON',
                    titulo: 'A resposta volta pela rede',
                    texto: '<code>201</code> significa "criado". Se alguma regra tivesse barrado, viria <code>400</code> com a lista de mensagens; se o banco tivesse caído, <code>500</code>.',
                    arquivo: ARQUIVOS.rotas,
                },
                {
                    de: 'servico', para: 'controladora', tipo: 'retorno',
                    rotulo: 'Emprestimo',
                    titulo: 'O serviço entrega o dado pronto',
                    texto: 'O serviço confere o código HTTP e converte o corpo em objeto. Se a resposta não fosse de sucesso, ele lançaria um erro com a mensagem vinda da API — e a controladora cairia no <code>catch</code>.',
                    arquivo: ARQUIVOS.servico,
                },
                {
                    de: 'controladora', para: 'visao', tipo: 'chamada',
                    rotulo: 'exibirEmprestimoRegistrado( emprestimo )',
                    titulo: 'A controladora manda exibir',
                    texto: 'Ela diz <em>o que</em> mostrar; a visão decide <em>como</em>. Trocar a tela inteira por outra implementação de <code>VisaoEmprestimos</code> não mudaria uma linha da controladora.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'controladora', para: 'servico', tipo: 'chamada',
                    rotulo: 'listarEmAberto()  — atualiza a tabela',
                    titulo: 'E a lista é recarregada',
                    texto: 'Logo depois, a controladora chama <code>atualizarLista()</code>, que refaz todo o caminho de leitura: serviço → rotas → gestor → repositório → banco, agora com um <code>SELECT</code>. É o cenário <strong>Abrir a tela</strong>.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'visao', para: 'usuario', tipo: 'retorno',
                    rotulo: 'mensagem verde e tabela atualizada',
                    titulo: 'Fim do caminho',
                    texto: 'A visão escreve "Empréstimo registrado. Devolver até…", limpa o formulário e redesenha a tabela. Você vê o resultado — e o livro está salvo no banco.',
                    arquivo: ARQUIVOS.visao,
                },
            ],
        },

        {
            id: 'listar',
            titulo: 'Abrir a tela',
            resumo: 'O caminho de leitura, sem escrever nada no banco. É o que acontece quando a página carrega e sempre que a tabela precisa ser atualizada.',
            passos: [
                {
                    de: 'usuario', para: 'visao', tipo: 'chamada',
                    rotulo: 'abre /emprestimos no navegador',
                    titulo: 'A página é montada',
                    texto: 'O <code>index</code> escolhe a página pelo endereço, insere o HTML e cria as três classes: visão, serviço e controladora. Depois chama <code>controladora.iniciar()</code>.',
                    arquivo: ARQUIVOS.visao,
                },
                {
                    de: 'visao', para: 'controladora', tipo: 'chamada',
                    rotulo: 'iniciar()',
                    titulo: 'A controladora liga os eventos',
                    texto: 'Primeiro ela registra o que fazer quando o usuário emprestar ou devolver (<code>aoRegistrar</code> e <code>aoDevolver</code>). Só então busca os dados.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'controladora', para: 'servico', tipo: 'chamada',
                    rotulo: 'listarLivros() e listarLeitores() ao mesmo tempo',
                    titulo: 'Duas requisições em paralelo',
                    texto: 'Com <code>Promise.all</code>, as duas chamadas saem juntas e a controladora espera as duas terminarem — em vez de esperar uma para só então começar a outra.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'servico', para: 'rotas', tipo: 'rede',
                    rotulo: 'GET /livros   ·   GET /leitores',
                    titulo: 'Duas rotas de leitura',
                    texto: 'Cada uma cai em seu próprio arquivo de rotas, que monta o repositório correspondente e pede a lista.',
                    arquivo: ARQUIVOS.servico,
                },
                {
                    de: 'rotas', para: 'repositorio', tipo: 'chamada',
                    rotulo: 'obterTodos()',
                    titulo: 'Leitura simples não passa pelo gestor',
                    texto: 'Listar livros e leitores não tem regra de negócio nenhuma, então a rota vai direto ao repositório. O gestor existe para coordenar regras — e aqui não há nenhuma.',
                    arquivo: ARQUIVOS.repositorioLivros,
                },
                {
                    de: 'repositorio', para: 'banco', tipo: 'sql',
                    rotulo: 'SELECT id, titulo, autor, ano FROM livro ORDER BY titulo',
                    titulo: 'A consulta',
                    texto: 'Sem <code>?</code> desta vez: não há valor vindo de fora, então a consulta pode ser executada direto.',
                    arquivo: ARQUIVOS.repositorioLivros,
                },
                {
                    de: 'banco', para: 'servico', tipo: 'retorno',
                    rotulo: 'linhas → objetos → JSON',
                    titulo: 'A volta, em três formatos',
                    texto: 'O banco devolve linhas; o repositório as transforma em objetos <code>Livro</code>; a rota transforma os objetos em JSON. Cada camada fala a língua da camada seguinte.',
                    arquivo: ARQUIVOS.repositorioLivros,
                },
                {
                    de: 'servico', para: 'controladora', tipo: 'retorno',
                    rotulo: 'Livro[]  e  Leitor[]',
                    titulo: 'As duas listas chegaram',
                    texto: '<code>Promise.all</code> só continua quando as duas respostas chegam. Se qualquer uma falhar, a controladora cai no <code>catch</code> e mostra o erro.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'controladora', para: 'visao', tipo: 'chamada',
                    rotulo: 'exibirOpcoes( livros, leitores )',
                    titulo: 'Os selects são preenchidos',
                    texto: 'A visão recria as opções dos dois campos, começando por "Escolha um livro" e "Escolha um leitor".',
                    arquivo: ARQUIVOS.visao,
                },
                {
                    de: 'controladora', para: 'servico', tipo: 'chamada',
                    rotulo: 'listarEmAberto()',
                    titulo: 'Agora a tabela',
                    texto: 'Uma terceira requisição, <code>GET /emprestimos</code>. Esta passa pelo gestor, porque prazo, dias de atraso e multa precisam ser calculados para hoje.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'servico', para: 'gestor', tipo: 'rede',
                    rotulo: 'GET /emprestimos  →  listarEmAberto( hoje )',
                    titulo: 'Aqui o gestor entra',
                    texto: 'O gestor busca os empréstimos em aberto no repositório e converte cada um em dados, perguntando à entidade a data limite, os dias de atraso e a multa de hoje.',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'gestor', para: 'entidade', tipo: 'chamada',
                    rotulo: 'dataLimite() · diasDeAtraso( hoje ) · calcularMulta( hoje )',
                    titulo: 'As regras R1 e R2, na entidade',
                    texto: 'Prazo de 7 dias e multa de R$ 1,00 por dia de atraso são constantes dentro de <code>Emprestimo</code>. Nada disso está guardado no banco: é calculado toda vez, a partir da data do empréstimo.',
                    destaque: 'regra',
                    arquivo: ARQUIVOS.emprestimo,
                },
                {
                    de: 'entidade', para: 'controladora', tipo: 'retorno',
                    rotulo: 'lista pronta, com multa calculada',
                    titulo: 'A resposta sobe',
                    texto: 'Entidade → gestor → rota → rede → serviço → controladora. Cada camada devolve o que a de cima espera, e nenhuma precisa conhecer a de baixo.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'controladora', para: 'visao', tipo: 'chamada',
                    rotulo: 'exibirEmprestimos( emprestimos )',
                    titulo: 'A tabela é desenhada',
                    texto: 'A visão cria uma linha por empréstimo, com o botão Devolver, e esconde o aviso de "nenhum empréstimo" se houver algum.',
                    arquivo: ARQUIVOS.visao,
                },
                {
                    de: 'visao', para: 'usuario', tipo: 'retorno',
                    rotulo: 'a tela pronta',
                    titulo: 'Tela carregada',
                    texto: 'Três requisições, nenhuma escrita no banco. A tela está pronta para a próxima ação.',
                    arquivo: ARQUIVOS.visao,
                },
            ],
        },

        {
            id: 'devolver',
            titulo: 'Devolver um livro',
            resumo: 'O botão Devolver da tabela. Mostra a entidade sendo usada para decidir e para calcular: ela recusa uma devolução repetida e diz quanto é a multa.',
            passos: [
                {
                    de: 'usuario', para: 'visao', tipo: 'chamada',
                    rotulo: 'clica em Devolver na linha da tabela',
                    titulo: 'Um evento para todos os botões',
                    texto: 'A visão não põe um evento em cada botão: põe um só na tabela e descobre qual botão foi clicado pelo <code>data-id</code>. Assim os botões criados depois já funcionam.',
                    arquivo: ARQUIVOS.visao,
                },
                {
                    de: 'visao', para: 'controladora', tipo: 'chamada',
                    rotulo: 'devolver( id )',
                    titulo: 'A visão passa só o id',
                    texto: 'É tudo o que a controladora precisa saber. Nada de elemento HTML atravessa essa fronteira.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'controladora', para: 'servico', tipo: 'chamada',
                    rotulo: 'devolver( id )',
                    titulo: 'E a controladora repassa',
                    texto: 'Mesmo padrão do empréstimo: a controladora pede, espera e depois manda exibir.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'servico', para: 'rotas', tipo: 'rede',
                    rotulo: 'PATCH /emprestimos/7/devolucao',
                    titulo: 'PATCH, não POST',
                    texto: 'O empréstimo já existe; o que muda é um pedaço dele — a data de devolução. <code>PATCH</code> é o verbo para alteração parcial. O id vai no endereço.',
                    arquivo: ARQUIVOS.servico,
                },
                {
                    de: 'rotas', para: 'gestor', tipo: 'chamada',
                    rotulo: 'devolver( id, hoje )',
                    titulo: 'A rota lê o id do endereço',
                    texto: 'O <code>:id</code> declarado na rota vira um parâmetro. A rota o entrega ao gestor junto com a data de hoje.',
                    arquivo: ARQUIVOS.rotas,
                },
                {
                    de: 'gestor', para: 'repositorio', tipo: 'chamada',
                    rotulo: 'obterEmAbertoPorId( id )',
                    titulo: 'Busca só entre os que estão em aberto',
                    texto: 'A consulta já filtra por <code>data_devolucao IS NULL</code>. Se vier <code>null</code>, o gestor lança "Empréstimo não encontrado ou já devolvido."',
                    arquivo: ARQUIVOS.repositorio,
                },
                {
                    de: 'repositorio', para: 'gestor', tipo: 'retorno',
                    rotulo: 'Emprestimo',
                    titulo: 'O objeto montado a partir de três tabelas',
                    texto: 'A consulta junta <code>emprestimo</code>, <code>livro</code> e <code>leitor</code> com <code>JOIN</code>, e o repositório monta de uma vez o empréstimo com o livro e o leitor dentro.',
                    arquivo: ARQUIVOS.repositorio,
                },
                {
                    de: 'gestor', para: 'entidade', tipo: 'chamada',
                    rotulo: 'emprestimo.devolver( hoje )',
                    titulo: 'Regra R5 — a entidade se defende',
                    texto: 'Quem recusa uma devolução repetida, ou com data anterior ao empréstimo, é o próprio objeto <code>Emprestimo</code>. Ele lança <code>DominioException</code>. O gestor não precisa lembrar dessa regra.',
                    destaque: 'regra',
                    arquivo: ARQUIVOS.emprestimo,
                },
                {
                    de: 'gestor', para: 'repositorio', tipo: 'chamada',
                    rotulo: 'registrarDevolucao( emprestimo.id, hoje )',
                    titulo: 'Só então grava',
                    texto: 'A entidade aceitou a devolução em memória; agora o repositório registra a data no banco.',
                    arquivo: ARQUIVOS.repositorio,
                },
                {
                    de: 'repositorio', para: 'banco', tipo: 'sql',
                    rotulo: 'UPDATE emprestimo SET data_devolucao = ? WHERE id = ?',
                    titulo: 'Aqui a devolução é salva',
                    texto: 'Um <code>UPDATE</code>, não um <code>DELETE</code>: o empréstimo continua no histórico, agora com data de devolução preenchida. É isso que o tira da lista de "em aberto".',
                    destaque: 'grava',
                    arquivo: ARQUIVOS.repositorio,
                },
                {
                    de: 'banco', para: 'gestor', tipo: 'retorno',
                    rotulo: 'linha alterada',
                    titulo: 'Gravado',
                    texto: 'Falta montar a resposta — e ela inclui a multa.',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'gestor', para: 'entidade', tipo: 'chamada',
                    rotulo: 'diasDeAtraso( hoje ) · calcularMulta( hoje )',
                    titulo: 'Regras R1 e R2 — a conta da multa',
                    texto: 'Dias de atraso é a diferença entre hoje e a data limite; a multa é esse número vezes R$ 1,00. A conta é da entidade, e o gestor só a coloca na resposta.',
                    destaque: 'regra',
                    arquivo: ARQUIVOS.emprestimo,
                },
                {
                    de: 'entidade', para: 'servico', tipo: 'rede',
                    rotulo: '200 OK  { diasDeAtraso: 3, multa: 3.0 }',
                    titulo: 'A resposta volta',
                    texto: 'Gestor → rota → JSON → rede → serviço, o mesmo caminho de volta de sempre.',
                    arquivo: ARQUIVOS.rotas,
                },
                {
                    de: 'servico', para: 'controladora', tipo: 'retorno',
                    rotulo: 'Devolucao',
                    titulo: 'A controladora decide o que exibir',
                    texto: 'Com multa maior que zero ou sem multa, o texto muda — mas quem escreve as palavras e as pinta de verde é a visão.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'controladora', para: 'visao', tipo: 'chamada',
                    rotulo: 'exibirDevolucao( devolucao )  +  atualizarLista()',
                    titulo: 'Mensagem e tabela',
                    texto: '"Livro devolvido com 3 dia(s) de atraso. Multa: R$ 3,00." E a tabela é recarregada: o empréstimo devolvido some dela.',
                    arquivo: ARQUIVOS.visao,
                },
            ],
        },

        {
            id: 'erro',
            titulo: 'Quando uma regra barra',
            resumo: 'O mesmo começo de Emprestar um livro, mas o livro escolhido já está com outra pessoa. Mostra por onde um erro de regra de negócio sobe até virar a mensagem vermelha da tela.',
            passos: [
                {
                    de: 'usuario', para: 'visao', tipo: 'chamada',
                    rotulo: 'escolhe um livro que já está emprestado',
                    titulo: 'Nada impede o clique',
                    texto: 'A tela não sabe quais livros estão emprestados — e não deveria saber. Quem guarda essa regra é o back-end.',
                },
                {
                    de: 'visao', para: 'servico', tipo: 'chamada',
                    rotulo: 'registrar( livroId, leitorId )  — via controladora',
                    titulo: 'O caminho de ida é o mesmo',
                    texto: 'Visão → controladora → serviço, exatamente como no cenário Emprestar um livro.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'servico', para: 'gestor', tipo: 'rede',
                    rotulo: 'POST /emprestimos  →  registrar( dados, hoje )',
                    titulo: 'Chega ao gestor',
                    texto: 'A rota entrega os dados ao gestor, que busca o livro e o leitor e começa a verificar as regras.',
                    arquivo: ARQUIVOS.rotas,
                },
                {
                    de: 'gestor', para: 'repositorio', tipo: 'chamada',
                    rotulo: 'livroEstaEmprestado( livro.id )',
                    titulo: 'A verificação da regra R4',
                    texto: 'Mesma pergunta do cenário anterior — mas desta vez a resposta é outra.',
                    arquivo: ARQUIVOS.repositorio,
                },
                {
                    de: 'repositorio', para: 'gestor', tipo: 'retorno',
                    rotulo: 'true — já está emprestado',
                    titulo: 'A regra foi violada',
                    texto: 'Existe um empréstimo em aberto para este livro. O gestor para aqui.',
                    destaque: 'erro',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'gestor', para: 'rotas', tipo: 'erro',
                    rotulo: 'throw DominioException( "O livro já está emprestado." )',
                    titulo: 'Erro de regra, não de programa',
                    texto: '<code>DominioException</code> existe para separar "os dados não servem" de "o sistema quebrou". Nada foi gravado: o INSERT nunca chegou a acontecer.',
                    destaque: 'erro',
                    arquivo: ARQUIVOS.gestor,
                },
                {
                    de: 'rotas', para: 'servico', tipo: 'rede',
                    rotulo: '400 Bad Request  { mensagens: [ ... ] }',
                    titulo: 'A exceção vira código HTTP',
                    texto: 'Um único <code>try/catch</code>, compartilhado por todas as rotas, traduz <code>DominioException</code> em <code>400</code> e <code>RepositorioException</code> em <code>500</code>.',
                    destaque: 'erro',
                    arquivo: ARQUIVOS.rotas,
                },
                {
                    de: 'servico', para: 'controladora', tipo: 'erro',
                    rotulo: 'throw Error( "O livro já está emprestado." )',
                    titulo: 'E o código HTTP vira exceção de novo',
                    texto: 'O serviço vê que a resposta não foi de sucesso e lança um erro com a mensagem da API. Para a controladora, é um <code>catch</code> igual a qualquer outro.',
                    destaque: 'erro',
                    arquivo: ARQUIVOS.servico,
                },
                {
                    de: 'controladora', para: 'visao', tipo: 'chamada',
                    rotulo: 'exibirErro( mensagem )',
                    titulo: 'Um único lugar para tratar erro',
                    texto: 'Todo método da controladora tem o mesmo <code>catch</code>, e ele sempre termina aqui. Não importa se o erro nasceu de uma regra, da rede ou do banco.',
                    arquivo: ARQUIVOS.controladora,
                },
                {
                    de: 'visao', para: 'usuario', tipo: 'retorno',
                    rotulo: 'faixa vermelha com a mensagem',
                    titulo: 'A mensagem que você vê',
                    texto: 'A mesma frase escrita lá no gestor chega intacta à tela. E a tabela não muda, porque nada mudou no banco.',
                    destaque: 'erro',
                    arquivo: ARQUIVOS.visao,
                },
            ],
        },
    ];

    Guia.dados.fluxo = { atores, cenarios };

})( window.Guia );
